name: Déployer sur GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: "https://ms-prestige-api.vercel.app"

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm ci

      - name: Construire le projet
        run: npm run build

      - name: Déployer sur gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
